package com.acloudysky.studentbook;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import io.swagger.annotations.ApiModel;

@SpringBootApplication
@ApiModel(description="Generated by the Spring intializer. It is the lanunching point for the application. ")
public class SpringBoot2RestServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringBoot2RestServiceApplication.class, args);
	}
}
